### ISSUE TITLE
Add `get_version` query call on all canisters

### ISSUE THREAD

**Issue by harshbaz** [go-bazzinga/hot-or-not-backend-canister#212]
Right now only way to tell if a canister has not updated is by comparing candid, which still does not tell us how old the deployed version is. We can keep a number counter which can be incremented on update and should be returned by the `get_version` query call.

edit: more info can be added like date (update created & update happening), commit sha, etc.

**Comment by saikatdas0790** [comment]
@ravibazz will be eventually adding a canister_metadata_details method that will expose versioning data for external consumers and internallly will get called for upgrade orchestration
