### ISSUE TITLE
Add filters in `post_cache` canister

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/hot-or-not-backend-canister#228]
## Description

Avoid giving out reference to posts which are not valid. (posts are not present or canister is not useable).

**Comment by harshbaz** [comment]
Filters to be applied for both feed:
- is it a nsfw video
- stuck/deleted/reference does not exist canister videos

Filter for hot or not feed
- prefer videos first which are not more than 48h old
- then return rest of the videos
