### ISSUE TITLE
get_top_posts_aggregated_from_canisters_on_this_network_for_home_feed_cursor returns duplicates

### ISSUE THREAD

**Issue by rupansh-gob** [go-bazzinga/hot-or-not-backend-canister#268]
Reproduction:

First Cursor: start = 10, end = 30
```
details PostDetails { canister_id: Principal { len: 10, bytes: [0, 0, 0, 0, 1, 192, 9, 158, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, post_id: 109, uid: "480ffe50b36c434ebfe58ddd2d15cabc" }
```

Second cursor: start = 30, end = 50
```
details PostDetails { canister_id: Principal { len: 10, bytes: [0, 0, 0, 0, 1, 192, 9, 158, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, post_id: 109, uid: "480ffe50b36c434ebfe58ddd2d15cabc" }
```

**Comment by rupansh-gob** [comment]
Not an issue,
Confusion arose as get_top_posts_aggregated_from_canisters_on_this_network_for_home_feed uses start & end as the cursor while
*_cursor api uses start & length

**Comment by s-go-bazzinga** [comment]
@ravibazz @rupansh-gob 

For all paginated APIs on our platform I think we should have a uniform assumption. They have to be cursor based. You pass in the ID of the last item you've received as the first argument and number of items you want as the 2nd argument and you're returned a list/array/vec of the expected items. Something like this:

```rust
get_paginated_items(id_of_last_item_received: u64, number_of_items_to_be_returned: u64, filter_criteria_if_any: Option<Filter>) -> Vec<Item> {}
```

In the implementation, we can then rely on iterator to iterate over the items asked for, apply any filters that are specified and then return the number of items asked for with an upper bound or iterated till the end of the list, whichever is earlier and then just return a cloned list of the items generated from the iteration.

Thoughts?
