### ISSUE TITLE
Scoped Delegated Identity

### ISSUE THREAD

**Issue by ravibazz** [go-bazzinga/hot-or-not-backend-canister#332]
## Description

After allowing namespace to store data in Individual canisters. We need Identities to have a meta data that will help us distinguish between identities coming from different namespaces.

## Tasks
- [ ] go-bazzinga/hot-or-not-web-leptos-ssr#269
- [ ] #349
- [ ] #355

**Comment by ravibazz** [comment]
Right now we are looking if signature can be send along with the function arguments and signature would contain meta data for the namespaces.

**Comment by harshitasrivastav28** [comment]
To be paused and other issues to be delegated to Ravi. - Decision made on 12th July

**Comment by Natasha-GB** [comment]
- Adding parameters on delegated identity, testing the same
- Refactor API
